# Generated by Django 4.2.4 on 2024-06-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='nazov',
            field=models.CharField(max_length=64),
        ),
    ]
