# Generated by Django 4.2.13 on 2024-06-07 09:14

from django.db import migrations, models
import django.db.models.deletion
import soc.models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0002_alter_tema_nazov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='dostupnost',
            field=models.ForeignKey(default=soc.models.get_default_availability, on_delete=django.db.models.deletion.CASCADE, to='soc.dostupnost'),
        ),
    ]
