# Generated by Django 4.2.4 on 2024-06-13 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0003_alter_tema_dostupnost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['-dostupnost', 'nazov'], 'verbose_name': 'Téma', 'verbose_name_plural': 'Témy'},
        ),
    ]
